import { Category, Product, Order, Review, StoreSetting } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-pendientes',
    name: 'Pendientes de Arcilla',
    slug: 'pendientes',
    description: 'Pendientes artesanales ultraligeros hechos a mano con arcilla polimérica. Texturas orgánicas, formas geométricas y fornituras hipoalergénicas.',
    image: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?w=800&auto=format&fit=crop&q=80',
    sortOrder: 1,
    productCount: 8,
  },
  {
    id: 'cat-pulseras',
    name: 'Pulseras & Brazaletes',
    slug: 'pulseras',
    description: 'Brazaletes con abalorios modelados a mano y cuentas de arcilla polimérica con detalles dorados y ajustables.',
    image: 'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?w=800&auto=format&fit=crop&q=80',
    sortOrder: 2,
    productCount: 4,
  },
  {
    id: 'cat-collares',
    name: 'Collares & Colgantes',
    slug: 'collares',
    description: 'Colgantes botánicos y medallones con texturas botánicas y acabados en terracota y lino.',
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&auto=format&fit=crop&q=80',
    sortOrder: 3,
    productCount: 4,
  },
  {
    id: 'cat-anillos',
    name: 'Anillos Esculpidos',
    slug: 'anillos',
    description: 'Anillos llamativos y minimalistas con gemas de arcilla y fornituras en acero dorado inoxidable.',
    image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&auto=format&fit=crop&q=80',
    sortOrder: 4,
    productCount: 3,
  },
  {
    id: 'cat-colecciones',
    name: 'Colecciones Especiales',
    slug: 'colecciones',
    description: 'Packs de regalo y ediciones limitadas con packaging de tela natural de lino y tarjeta dedicada.',
    image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&auto=format&fit=crop&q=80',
    sortOrder: 5,
    productCount: 3,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Pendientes Terracota Arch Boho',
    slug: 'pendientes-terracota-arch-boho',
    description: `Nuestros **Pendientes Terracota Arch Boho** son el icono de nuestra colección artesanal. Esculpidos a mano en arcilla polimérica de tonalidad terracota cálida con arco colgante texturizado y perno superior esmaltado en tono arena.\n\n### ✨ Características Principales:\n- **100% Hechos a Mano**: Cada par es único, cortado, horneado y pulido minuciosamente en nuestro taller.\n- **Ultraligeros**: Menos de 4 gramos de peso por pendiente. No notarás que los llevas puestos durante todo el día.\n- **Hipoalergénicos**: Pernos y cierres de acero inoxidable quirúrgico 316L con baño dorado de alta durabilidad.\n- **Resistentes al agua**: La arcilla polimérica cocida es flexible, duradera e impermeable.\n\n### 🌿 Consejos de Cuidado:\nGuardar en un lugar seco y evitar aplicar perfumes o lacas directamente sobre la pieza. Para limpiarlos, basta con pasar un paño suave húmedo con un poco de agua o alcohol suave.`,
    shortDescription: 'Pendientes en forma de arco bohemio en terracota y arena. Ultraligeros con acero hipoalergénico.',
    price: 24.90,
    comparePrice: 29.90,
    costPrice: 4.50,
    stock: 12,
    sku: 'BOHO-EAR-001',
    materials: 'Arcilla polimérica de alta calidad, pernos de acero inoxidable quirúrgico hipoalergénico bañado en oro de 18k.',
    dimensions: '6.2 cm de largo x 3.2 cm de ancho',
    weightGrams: 4,
    images: [
      'https://images.unsplash.com/photo-1630019852942-f89202989a59?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&auto=format&fit=crop&q=80',
    ],
    isFeatured: true,
    isActive: true,
    categoryId: 'cat-pendientes',
    createdAt: '2026-08-10T10:00:00Z',
    rating: 5,
    reviewCount: 18,
  },
  {
    id: 'prod-2',
    name: 'Maxi Aros Mármol Salvia & Nude',
    slug: 'maxi-aros-marmol-salvia-nude',
    description: `Elegantes aros de formato medio con efecto marmoleado conseguido a mano mezclando arcilla verde salvia, blanco lino y toques dorados.\n\nUn diseño moderno y versátil ideal tanto para looks casuales de diario como para eventos especiales.`,
    shortDescription: 'Aros con efecto marmoleado en arcilla polimérica tono salvia y nude con motas doradas.',
    price: 22.50,
    comparePrice: null,
    costPrice: 3.80,
    stock: 8,
    sku: 'BOHO-EAR-002',
    materials: 'Arcilla polimérica marmoleada, aros de latón libre de níquel con baño de oro 24k.',
    dimensions: '4.5 cm de diámetro',
    weightGrams: 3,
    images: [
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1630019852942-f89202989a59?w=800&auto=format&fit=crop&q=80',
    ],
    isFeatured: true,
    isActive: true,
    categoryId: 'cat-pendientes',
    createdAt: '2026-08-12T11:00:00Z',
    rating: 5,
    reviewCount: 12,
  },
  {
    id: 'prod-3',
    name: 'Pendientes Botánicos Textura Gingko',
    slug: 'pendientes-botanicos-textura-gingko',
    description: `Inspirados en las hojas del árbol sagrado Gingko Biloba. Textura en relieve estampada a mano en arcilla color mostaza tostado y arena cálida.\n\nCada detalle de las venas de la hoja ha sido esculpido a mano con herramientas de modelado de precisión.`,
    shortDescription: 'Diseño botánico inspirado en la hoja de Gingko. Textura en relieve y tono mostaza tostado.',
    price: 26.00,
    comparePrice: 32.00,
    costPrice: 5.00,
    stock: 15,
    sku: 'BOHO-EAR-003',
    materials: 'Arcilla polimérica horneada a doble temperatura, enganches de plata 925 bañada en oro.',
    dimensions: '5.8 cm x 3.5 cm',
    weightGrams: 4,
    images: [
      'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1630019852942-f89202989a59?w=800&auto=format&fit=crop&q=80',
    ],
    isFeatured: true,
    isActive: true,
    categoryId: 'cat-pendientes',
    createdAt: '2026-08-14T09:30:00Z',
    rating: 5,
    reviewCount: 9,
  },
  {
    id: 'prod-4',
    name: 'Collar Medallón Solsticio Arcilla & Oro',
    slug: 'collar-medallon-solsticio-arcilla-oro',
    description: `Colgante con medallón central circular en arcilla polimérica texturizada con rayos de sol y pan de oro incrustado.\n\nMontado sobre una fina cadena veneciana de acero inoxidable bañada en oro de 18k con extensor para ajustar la altura a tu escote favorito.`,
    shortDescription: 'Colgante artesanal con medallón de arcilla y motivos solares en pan de oro.',
    price: 34.00,
    comparePrice: 39.00,
    costPrice: 6.50,
    stock: 7,
    sku: 'BOHO-NECK-001',
    materials: 'Arcilla polimérica horneada, pan de oro sellado con resina vegetal ecológica, cadena de acero 316L.',
    dimensions: 'Medallón 2.8 cm, cadena ajustable de 45 a 50 cm',
    weightGrams: 8,
    images: [
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?w=800&auto=format&fit=crop&q=80',
    ],
    isFeatured: true,
    isActive: true,
    categoryId: 'cat-collares',
    createdAt: '2026-08-15T15:20:00Z',
    rating: 5,
    reviewCount: 14,
  },
  {
    id: 'prod-5',
    name: 'Pulsera Ajustable Cuentas de Arcilla & Amatista',
    slug: 'pulsera-ajustable-cuentas-arcilla-amatista',
    description: `Pulsera artesanal compuesta por discos de arcilla polimérica modelados a mano en gama cromática cálida (terracota, crema y chocolate) combinados con chips de cuarzo rosa y amatista natural.`,
    shortDescription: 'Pulsera bohemia con discos de arcilla modelados a mano y minerales naturales.',
    price: 19.50,
    comparePrice: null,
    costPrice: 3.20,
    stock: 14,
    sku: 'BOHO-BRAC-001',
    materials: 'Discos de arcilla polimérica, minerales naturales, cordón de macramé encerado resistente al agua.',
    dimensions: 'Ajustable de 15 cm a 22 cm de contorno',
    weightGrams: 6,
    images: [
      'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&auto=format&fit=crop&q=80',
    ],
    isFeatured: false,
    isActive: true,
    categoryId: 'cat-pulseras',
    createdAt: '2026-08-16T12:00:00Z',
    rating: 5,
    reviewCount: 6,
  },
  {
    id: 'prod-6',
    name: 'Anillo Chunky Geométrico Terracota',
    slug: 'anillo-chunky-geometrico-terracota',
    description: `Anillo llamativo de inspiración arquitectónica esculpido en una sola pieza de arcilla polimérica con acabado mate pulido.\n\nLigero y sumamente cómodo de llevar, aporta un toque de personalidad artística a tus manos.`,
    shortDescription: 'Anillo estilo chunky de diseño escultórico en arcilla polimérica mate.',
    price: 18.00,
    comparePrice: 22.00,
    costPrice: 2.50,
    stock: 9,
    sku: 'BOHO-RING-001',
    materials: 'Arcilla polimérica maciza de alta resistencia.',
    dimensions: 'Base abierta adaptable de talla 12 a 18',
    weightGrams: 5,
    images: [
      'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1630019852942-f89202989a59?w=800&auto=format&fit=crop&q=80',
    ],
    isFeatured: false,
    isActive: true,
    categoryId: 'cat-anillos',
    createdAt: '2026-08-17T18:00:00Z',
    rating: 4,
    reviewCount: 4,
  },
  {
    id: 'prod-7',
    name: 'Pack Regalo Taller Bohoart (Pendientes + Pulsera)',
    slug: 'pack-regalo-taller-bohoart',
    description: `El pack más especial para regalar (o autoregalarte). Incluye nuestros Pendientes Terracota Arch Boho y la Pulsera Ajustable de Cuentas, presentados en una exclusiva caja artesanal con saquito de lino natural, tarjeta dedicatoria y flores secas preservadas.`,
    shortDescription: 'Caja regalo completa con pendientes arch, pulsera artesanal y packaging de lino.',
    price: 39.90,
    comparePrice: 44.40,
    costPrice: 8.00,
    stock: 5,
    sku: 'BOHO-SET-001',
    materials: 'Conjunto de arcilla polimérica, acero 316L bañado en oro y saquito de lino ecológico.',
    dimensions: 'Caja regalo 12 x 12 x 4 cm',
    weightGrams: 75,
    images: [
      'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1630019852942-f89202989a59?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?w=800&auto=format&fit=crop&q=80',
    ],
    isFeatured: true,
    isActive: true,
    categoryId: 'cat-colecciones',
    createdAt: '2026-08-18T10:00:00Z',
    rating: 5,
    reviewCount: 11,
  },
  {
    id: 'prod-8',
    name: 'Pendientes Gota Cascada Arena & Terracota',
    slug: 'pendientes-gota-cascada-arena-terracota',
    description: `Diseño articulado compuesto por tres eslabones móviles en caída vertical. La interacción de colores arena, arcilla cruda y terracota aporta un movimiento fluido y armonioso que estiliza el cuello.`,
    shortDescription: 'Pendientes articulados en tres piezas con movimiento suave y tonos tierra.',
    price: 27.50,
    comparePrice: null,
    costPrice: 4.80,
    stock: 10,
    sku: 'BOHO-EAR-004',
    materials: 'Arcilla polimérica multicapa, aros de unión y cierres en latón hipoalergénico bañado en oro.',
    dimensions: '7.0 cm x 2.4 cm',
    weightGrams: 4,
    images: [
      'https://images.unsplash.com/photo-1630019852942-f89202989a59?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&auto=format&fit=crop&q=80',
    ],
    isFeatured: true,
    isActive: true,
    categoryId: 'cat-pendientes',
    createdAt: '2026-08-19T14:15:00Z',
    rating: 5,
    reviewCount: 7,
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    productId: 'prod-1',
    productName: 'Pendientes Terracota Arch Boho',
    authorName: 'Carmen Morales',
    authorEmail: 'carmen.m@gmail.com',
    rating: 5,
    title: '¡No pesan absolutamente nada!',
    comment: 'Tenía miedo de que al ser un pendiente grandecito me tirase del lóbulo, pero son ligerísimos como una pluma. El color terracota es precioso y el empaquetado vino con mucho mimo. ¡Repetiré seguro!',
    isApproved: true,
    isVerifiedBuyer: true,
    createdAt: '2026-08-20T16:20:00Z',
  },
  {
    id: 'rev-2',
    productId: 'prod-1',
    productName: 'Pendientes Terracota Arch Boho',
    authorName: 'Laura Benítez',
    authorEmail: 'laurab@hotmail.com',
    rating: 5,
    title: 'Calidad insuperable',
    comment: 'Se nota el trabajo a mano que tienen detrás. Los acabados son perfectos y no me dan ninguna alergia en las orejas, que las tengo súper sensibles.',
    isApproved: true,
    isVerifiedBuyer: true,
    createdAt: '2026-08-22T11:45:00Z',
  },
  {
    id: 'rev-3',
    productId: 'prod-4',
    productName: 'Collar Medallón Solsticio Arcilla & Oro',
    authorName: 'Sonia Garrido',
    authorEmail: 'sonia.gar@gmail.com',
    rating: 5,
    title: 'Un colgante mágico',
    comment: 'Llegó en 48 horas a Sevilla. El detalle del pan de oro resplandece al sol de una forma súper elegante. Todo el mundo me pregunta de dónde es.',
    isApproved: true,
    isVerifiedBuyer: true,
    createdAt: '2026-08-24T09:15:00Z',
  },
  {
    id: 'rev-4',
    productId: 'prod-7',
    productName: 'Pack Regalo Taller Bohoart',
    authorName: 'Elena Vives',
    authorEmail: 'elena.v@outlook.es',
    rating: 5,
    title: 'El regalo perfecto para mi hermana',
    comment: 'La presentación en la caja con el saquito de lino y la tarjetita personalizada dejó a mi hermana fascinada por su cumpleaños. ¡Muchas gracias por el cariño!',
    isApproved: true,
    isVerifiedBuyer: true,
    createdAt: '2026-08-25T17:30:00Z',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1001',
    orderNumber: 'BH-2026-1001',
    customerName: 'Lucía Fernández Ruiz',
    customerEmail: 'lucia.fernandez@gmail.com',
    customerPhone: '+34 612 345 678',
    shippingAddress: 'Calle Alcalá 142, 3º B',
    city: 'Madrid',
    postalCode: '28009',
    province: 'Madrid',
    country: 'España',
    subtotal: 47.40,
    shippingCost: 0.00,
    totalAmount: 47.40,
    status: 'PAID',
    paymentMethod: 'PAYPAL',
    paypalOrderId: 'PAYPAL-TX-88392104',
    trackingNumber: 'CORREOS-ES-992819',
    notes: 'Entregar preferiblemente por las mañanas.',
    createdAt: '2026-08-27T10:14:00Z',
    items: [
      {
        id: 'item-1',
        orderId: 'ord-1001',
        productId: 'prod-1',
        productName: 'Pendientes Terracota Arch Boho',
        productImage: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?w=800&auto=format&fit=crop&q=80',
        unitPrice: 24.90,
        quantity: 1,
      },
      {
        id: 'item-2',
        orderId: 'ord-1001',
        productId: 'prod-2',
        productName: 'Maxi Aros Mármol Salvia & Nude',
        productImage: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&auto=format&fit=crop&q=80',
        unitPrice: 22.50,
        quantity: 1,
      },
    ],
  },
  {
    id: 'ord-1002',
    orderNumber: 'BH-2026-1002',
    customerName: 'Marta Soler Puig',
    customerEmail: 'marta.soler@gmail.com',
    customerPhone: '+34 689 443 211',
    shippingAddress: 'Passeig de Gràcia 54, 4º 1ª',
    city: 'Barcelona',
    postalCode: '08007',
    province: 'Barcelona',
    country: 'España',
    subtotal: 39.90,
    shippingCost: 3.95,
    totalAmount: 43.85,
    status: 'PROCESSING',
    paymentMethod: 'PAYPAL',
    paypalOrderId: 'PAYPAL-TX-44910294',
    trackingNumber: null,
    notes: null,
    createdAt: '2026-08-28T14:40:00Z',
    items: [
      {
        id: 'item-3',
        orderId: 'ord-1002',
        productId: 'prod-7',
        productName: 'Pack Regalo Taller Bohoart (Pendientes + Pulsera)',
        productImage: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&auto=format&fit=crop&q=80',
        unitPrice: 39.90,
        quantity: 1,
      },
    ],
  },
  {
    id: 'ord-1003',
    orderNumber: 'BH-2026-1003',
    customerName: 'Beatriz Navarro Gómez',
    customerEmail: 'b.navarro@yahoo.es',
    customerPhone: '+34 654 876 543',
    shippingAddress: 'Avenida de la Constitución 18, 1º Izq',
    city: 'Valencia',
    postalCode: '46009',
    province: 'Valencia',
    country: 'España',
    subtotal: 26.00,
    shippingCost: 3.95,
    totalAmount: 29.95,
    status: 'SHIPPED',
    paymentMethod: 'PAYPAL',
    paypalOrderId: 'PAYPAL-TX-10294812',
    trackingNumber: 'GLS-ES-883719001',
    notes: null,
    createdAt: '2026-08-26T09:12:00Z',
    items: [
      {
        id: 'item-4',
        orderId: 'ord-1003',
        productId: 'prod-3',
        productName: 'Pendientes Botánicos Textura Gingko',
        productImage: 'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=800&auto=format&fit=crop&q=80',
        unitPrice: 26.00,
        quantity: 1,
      },
    ],
  },
];

export const INITIAL_SETTINGS: StoreSetting = {
  id: 'store-default',
  storeName: 'Bohoart Jewelry',
  announcementText: '✨ Envíos gratis a toda España en pedidos a partir de 40€ | Joyas hechas a mano con amor ✨',
  freeShippingThreshold: 40.00,
  standardShippingCost: 3.95,
  paypalClientId: 'sb',
  contactEmail: 'hola@bohoartjoyeria.com',
  instagramUrl: 'https://instagram.com/bohoart.jewelry',
  maintenanceMode: false,
  maintenanceAllowedIps: '127.0.0.1, ::1',
  maintenanceTitle: '✨ Estamos preparando nuevas joyas en el taller ✨',
  maintenanceMessage: 'Nuestra tienda online se encuentra en mantenimiento durante unas horas para añadir nuevas colecciones artesanales en arcilla polimérica. ¡Volvemos muy pronto!',
};
